### ISSUE TITLE
通过版本号来判断更新

### ISSUE THREAD

**Issue by ix64** [hxm108/UnblockMusic-Client#2]
此处应该通过版本号来确认是否有更新
https://github.com/hxm108/UnblockMusic-Client/blob/978bcd27de6346a91cc293c90b87d64829442e7c/src/App.vue#L82

此处应该为更新提示。
https://github.com/hxm108/UnblockMusic-Client/blob/978bcd27de6346a91cc293c90b87d64829442e7c/src/App.vue#L83-L90

**Comment by ix64** [comment]
另外，你应该了解一下此项目中，使用的Service Worker。如果你只是部署于github pages。是不需要这部分更新检测的，Service Worker会自动完成。这部分检测只用于给本地运行的用户进行提醒。

**Comment by hxm108** [comment]
ServiceWorker会自动更新代码吗？

**Comment by ix64** [comment]
会自动更新缓存。参考 https://developer.mozilla.org/zh-CN/docs/Web/API/Service_Worker_API

**Comment by hxm108** [comment]
那直接删去本地更新检测部分？

**Comment by ix64** [comment]
可以的

**Comment by ix64** [comment]
这个功能也是1.3.2刚刚添加的

**Comment by hxm108** [comment]
因为也是第一次接触这个，难免会有些比较沙雕的错误 [笑哭]

**Comment by hxm108** [comment]
已根据 [9fd7177](https://github.com/ix64/unlock-music/commit/9fd7177ebbf29dccb7eef457be5614d363ac92c5)去本地更新
